### ISSUE TITLE
大佬求助

### ISSUE THREAD

**Issue by Jutean** [yjqiang/bili2.0#233] opened 2019-12-23 18:25 UTC
Traceback (most recent call last):
  File "C:\Program Files (x86)\bili2.0-master\run.py", line 48, in <module>
    dict_task = conf_loader.read_task()
  File "C:\Program Files (x86)\bili2.0-master\conf_loader.py", line 103, in read_task
    return var.read_task()
  File "C:\Program Files (x86)\bili2.0-master\conf_loader.py", line 76, in read_task
    return self.toml_load(self.file_task)
  File "C:\Program Files (x86)\bili2.0-master\conf_loader.py", line 42, in toml_load
    return toml.load(f)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\toml\decoder.py", line 134, in load
    return loads(f.read(), _dict, decoder)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\toml\decoder.py", line 225, in loads
    raise TomlDecodeError("Found invalid character in key name: '" +
toml.decoder.TomlDecodeError: Found invalid character in key name: '['. Try quoting the key name. (line 1 column 2 char 1)

**Comment by rabbit2rabbit** [comment] 2019-12-23 18:28
Duplicate of #39

**Closed** 2019-12-23 18:35 UTC

**Comment by yjqiang** [comment] 2019-12-23 22:32
https://github.com/yjqiang/bili2.0/issues/231
